version: "3.9"

services:
  api:
    build: .
    container_name: qwen-api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  mongo:
    image: mongo:6.0
    container_name: qwen-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
